name: Build and publish

on:
  push:
    tags: ['*']

jobs:
  lint-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Run linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46

  lint-ansible:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install linters
        run: sudo apt install -y ansible ansible-lint yamllint

      - name: Run yamllint
        run: yamllint --format colored --strict ./playbook.yml

      - name: Run ansible-lint
        run: ansible-lint ./playbook.yml

  build:
    needs: [lint-go, lint-ansible]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: tetafro
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/tetafro/socks5:${{ github.ref_name }}, ghcr.io/tetafro/socks5:latest
